### PR TITLE
alpine base image

### PR DESCRIPTION
**Pull request by ardimehist-r7**
@pascalandy what do you think of using this base image to bring the docker-logentries image total  size down to ~43MB. Initial testing has proven stable. Would you mind giving this a try?

### CODE REVIEW

**Comment by pascalandy** [comment]
Sure what is the tag?
I only see latest and 0.2 at the moment.

**Comment by pascalandy** [comment]
Also, I would say that nginx and redis dockerhub image are very well made. Look at there tags, very easy to understand what you are running.

**Comment by ardimehist-r7** [comment]
@pascalandy this hasn't been merged to master yet and not available via dockerhub. Can be built from repo however, until merged.

**Comment by jedi4ever** [comment]
@ardimehist-r7 @pascalandy - there is already a Dockerfile build file for using node-alpine - https://github.com/rapid7/docker-logentries/blob/master/Dockerfile.alpine

**Comment by ardimehist-r7** [comment]
@jedi4ever the difference is using the official alpine base image, rather than a 3rd party alpine build with prebuilt packages.

**Comment by jedi4ever** [comment]
@ardimehist-r7 👍 for that . Though using alpine:edge is not prefered , we'd better pin it to a specific version for debugging. Also with the proposed solution it would be best to track the node & npm version somewhere that was used in the build.

**Comment by ardimehist-r7** [comment]
@jedi4ever fair point, I'll look into suitable versions and update the PR

**Comment by pascalandy** [comment]
Hey guys,

Still looking for this image. I can't see it here - https://hub.docker.com/r/logentries/docker-logentries/tags/

**Comment by ardimehist-r7** [comment]
@pascalandy hey,
we'll have to trigger a build on docker hub as this is a separate branch for the time being. It should be available as 0.2.1 and latest later today. I'll post an update here once sorted

**Comment by ardimehist-r7** [comment]
@pascalandy the alpine base version is available as 0.2.1 https://hub.docker.com/r/logentries/docker-logentries/tags/

**Pull request merged**
